### ISSUE TITLE
When run: ! python fit_headpose.py  

### ISSUE THREAD

**Issue by muxiddin19** [zhangchenxu528/FACIAL#31]
Traceback (most recent call last):
  File "fit_headpose.py", line 24, in <module>
    facemodel = BFM()
  File "/content/FACIAL/face_render/load_data.py", line 12, in __init__
    self.meanshape = model['meanshape'] # mean face shape 
KeyError: 'meanshape'

**Comment by zhangchenxu528** [comment]
This issue has been resolved, please try again.
