### ISSUE TITLE
Error in 5.1.2 Train face2video by yourself (optional 2)

### ISSUE THREAD

**Issue by muxiddin19** [zhangchenxu528/FACIAL#44]
When I run the python train.py --blink_path '../video_preprocess/train1_openface/train1_512_audio.csv' --name train3 --model pose2vid --dataroot ./datasets/train3/ --netG local --ngf 32 --num_D 3 --tf_log --niter_fix_global 0 --label_nc 0 --no_instance --save_epoch_freq 2 --lr=0.0001 --resize_or_crop resize --no_flip --verbose --n_local_enhancers 1
faced this issue:
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
I am using a Linux server with #GPU is 2, is it related to this?
Please, any solution?

**Comment by muxiddin19** [comment]
When I add
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
in the models/networks_modified.py, I gace another issue related to cuda:
RuntimeError: CUDA error: out of memory

Any suggestions, please?

**Comment by muxiddin19** [comment]
Traceback (most recent call last):
  File "/workspace/FACIAL/face2vid/train.py", line 53, in <module>
    model = create_model(opt)
  File "/workspace/FACIAL/face2vid/models/models.py", line 21, in create_model
    model.initialize(opt)
  File "/workspace/FACIAL/face2vid/models/pose2vidHD_model.py", line 48, in initialize
    self.netG = networks.define_G(netG_input_nc, opt.output_nc, opt.ngf, opt.netG, 
  File "/workspace/FACIAL/face2vid/models/networks_modified.py", line 51, in define_G
    netG.cuda(gpu_ids[0])
  File "/root/miniconda3/envs/audio_face/lib/python3.9/site-packages/torch/nn/modules/module.py", line 680, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/root/miniconda3/envs/audio_face/lib/python3.9/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/audio_face/lib/python3.9/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/audio_face/lib/python3.9/site-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
  File "/root/miniconda3/envs/audio_face/lib/python3.9/site-packages/torch/nn/modules/module.py", line 680, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory

**Comment by zhangchenxu528** [comment]
Sorry, I use only a single GPU ( 1080 ti ) for training and can't offer any advice.
