### ISSUE TITLE
'deepspeech/input_node', does not exist in the graph

### ISSUE THREAD

**Issue by muxiddin19** [zhangchenxu528/FACIAL#54]
Thanks for the great work. However, when I run the python audio_preprocessing.py code, I face error:
Traceback (most recent call last):
  File "/home/ubuntu/muhiddin/FACIAL/audio2face/audio_preprocessing.py", line 61, in <module>
    processed_audio = process_audio(ds_fname, audio4deepspeech, fps)                # generate audio feature
  File "/home/ubuntu/muhiddin/FACIAL/audio2face/audio_preprocessing.py", line 39, in process_audio
    processed_audio = audio_handler.process(audio, fps)
  File "/home/ubuntu/muhiddin/FACIAL/audio2face/_utils/audio_handler.py", line 58, in process
    return self.convert_to_deepspeech(audio, fps)
  File "/home/ubuntu/muhiddin/FACIAL/audio2face/_utils/audio_handler.py", line 107, in convert_to_deepspeech
    input_tensor = graph.get_tensor_by_name('deepspeech/input_node:0')
  File "/home/ubuntu/anaconda3/envs/audio_face/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 4150, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/ubuntu/anaconda3/envs/audio_face/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 3974, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/ubuntu/anaconda3/envs/audio_face/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 4014, in _as_graph_element_locked
    raise KeyError("The name %s refers to a Tensor which does not "
KeyError: "The name 'deepspeech/input_node:0' refers to a Tensor which does not exist. The operation, 'deepspeech/input_node', does not exist in the graph."
Can you give some solution for this issue?

**Comment by muxiddin19** [comment]
I tried two different Linux GPU Servers but faced the same error. I use Tensorflow 2.4.1 and 2.8.0 simultaneously. Is it a cause for the problem? If yes, how to use Tensorflow 1. I could not install it due to the unavailability of the one. Please any suggestions?

**Comment by zhangchenxu528** [comment]
Tensorflow 2.0 does have this problem, and I don't know how to fix it. If you just use it for research, you can simply preprocess the audio feature with Colab.

**Comment by Arthurzhangsheng** [comment]
> Tensorflow 2.0 does have this problem, and I don't know how to fix it. If you just use it for research, you can simply preprocess the audio feature with Colab.

Unfortunately, the colab has no longer supported tf1. x since August this year, and the colab training program you provided can no longer run
